In [ ]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import numpy as np

In [ ]:
webpage=requests.get('https://books.toscrape.com/catalogue/page-2.html')

In [ ]:
webpage.encoding = 'utf-8'

In [ ]:
soup=BeautifulSoup(webpage.text,'lxml')

# print(soup.prettify())

In [ ]:
book_names = []
for book in soup.select('article.product_pod'):
    book_names.append(book.h3.a['title'])  # Access the title attribute directly

book_names

['In Her Wake',
 'How Music Works',
 'Foolproof Preserving: A Guide to Small Batch Jams, Jellies, Pickles, Condiments, and More: A Foolproof Guide to Making Small Batch Jams, Jellies, Pickles, Condiments, and More',
 'Chase Me (Paris Nights #2)',
 'Black Dust',
 'Birdsong: A Story in Pictures',
 "America's Cradle of Quarterbacks: Western Pennsylvania's Football Factory from Johnny Unitas to Joe Montana",
 'Aladdin and His Wonderful Lamp',
 'Worlds Elsewhere: Journeys Around Shakespeare’s Globe',
 'Wall and Piece',
 'The Four Agreements: A Practical Guide to Personal Freedom',
 'The Five Love Languages: How to Express Heartfelt Commitment to Your Mate',
 'The Elephant Tree',
 'The Bear and the Piano',
 "Sophie's World",
 'Penny Maybe',
 'Maude (1883-1993):She Grew Up with the country',
 'In a Dark, Dark Wood',
 'Behind Closed Doors',
 "You can't bury them all: Poems"]

In [ ]:
prices = soup.find_all('p', class_='price_color')

In [ ]:
price_list = []
for price in prices:
    price_list.append(price.text)

In [ ]:
pd.DataFrame({'name': book_names, 'Prices':price_list})

                                                 name  Prices
0                                         In Her Wake  £12.84
1                                     How Music Works  £37.32
2   Foolproof Preserving: A Guide to Small Batch J...  £30.52
3                          Chase Me (Paris Nights #2)  £25.27
4                                          Black Dust  £34.53
5                       Birdsong: A Story in Pictures  £54.64
6   America's Cradle of Quarterbacks: Western Penn...  £22.50
7                      Aladdin and His Wonderful Lamp  £53.13
8   Worlds Elsewhere: Journeys Around Shakespeare’...  £40.30
9                                      Wall and Piece  £44.18
10  The Four Agreements: A Practical Guide to Pers...  £17.66
11  The Five Love Languages: How to Express Heartf...  £31.05
12                                  The Elephant Tree  £23.82
13                             The Bear and the Piano  £36.89
14                                     Sophie's World  £15.94
15                                        Penny Maybe  £33.29
16     Maude (1883-1993):She Grew Up with the country  £18.02
17                               In a Dark, Dark Wood  £19.63
18                                Behind Closed Doors  £52.22
19                     You can't bury them all: Poems  £33.63

In [ ]:
final_df = pd.DataFrame()
for j in range(1, 50):
    webpage = requests.get(f'https://books.toscrape.com/catalogue/page-{j}.html')
    webpage.encoding = 'utf-8'
    soup = BeautifulSoup(webpage.text, 'lxml')
    book_names = []
    for book in soup.select('article.product_pod'):
        book_names.append(book.h3.a['title'])

    prices = soup.find_all('p', class_='price_color')
    price_list = []
    for price in prices:
        price_list.append(price.text)

    image = []
    for i in soup.find_all('img'):
        image.append(i['src'])



    stock = []
    for s in soup.find_all('p', class_='instock availability'):
        stock.append(s.text.strip())



    df = pd.DataFrame({'Name': book_names, 'Prices': price_list, 'Image':image, 'Stock': stock})
    final_df = pd.concat([final_df, df], ignore_index=True)

In [ ]:

final_df['Stock'] = final_df['Stock'].apply(lambda x: x.replace('In stock', 'Yes'))

In [ ]:

final_df['Stock'] = final_df['Stock'].apply(lambda x: x.replace('False', 'No'))

In [ ]:
final_df

,Name,Prices,Image,Stock
0,A Light in the Attic,£51.77,../media/cache/2c/da/2cdad67c44b002e7ead0cc356...,Yes
1,Tipping the Velvet,£53.74,../media/cache/26/0c/260c6ae16bce31c8f8c95dadd...,Yes
2,Soumission,£50.10,../media/cache/3e/ef/3eef99c9d9adef34639f51066...,Yes
3,Sharp Objects,£47.82,../media/cache/32/51/3251cf3a3412f53f339e42cac...,Yes
4,Sapiens: A Brief History of Humankind,£54.23,../media/cache/be/a5/bea5697f2534a2f86a3ef27b5...,Yes
...,...,...,...,...
975,Icing (Aces Hockey #2),£40.44,../media/cache/8d/1e/8d1e285bf672b2ea66879490c...,Yes
976,"Hawkeye, Vol. 1: My Life as a Weapon (Hawkeye #1)",£45.24,../media/cache/16/46/16460146a1a8b99c82da02736...,Yes
977,Having the Barbarian's Baby (Ice Planet Barbar...,£34.96,../media/cache/f4/83/f4835e9f3fdd8b8107bbb39a3...,Yes
978,"Giant Days, Vol. 1 (Giant Days #1-4)",£56.76,../media/cache/35/0b/350b1224dc46533851d5a3413...,Yes
979,"Fruits Basket, Vol. 1 (Fruits Basket #1)",£40.28,../media/cache/7c/c1/7cc13a8fb238202250e87843c...,Yes

In [ ]:
final_df.to_csv('books.csv')